blank_issues_enabled: false
contact_links:
  - name: Slack
    url: https://kubernetes.slack.com/archives/C019ZRGUEJC
    about: Participate in near real-time conversations with other Shipwright community members. Ask questions, get answers, build relationships.
  - name: GitHub Discussions
    url: https://github.com/shipwright-io/community/discussions
    about: Join in-depth discussions about everything Shipwright, propose new features, debate to your hearts content, and help shape our future!
  - name: Mailing Lists
    url: https://lists.cncf.io
    about: Do you love your email client and want to spend more time using it? Then this is the place for you! Ask questions and get announcements all from the safety of your inbox.
